function paperSpeedSummary()
    parms = make_parms( ...
        'threshold',2.5E-4, ...
        'sessions', {'J29c', 'J29g', 'J29i', 'M18b', 'M18c', 'M18d', 'M18e', 'M25c', 'M25d', 'J26b', 'J26c'}, ...
        'medianErrWidth', 15 ...
    );
    speedsByJancke(parms);
end